---
- name: Ensure docker is instelled
  hosts: all
  remote_user: ec2-user
  gather_facts: false
  become: true
  tasks:
    - name: Install Docker
      yum: name=docker

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes